[project]
name = "vitrine"
version = "0.1.0"
description = ""
authors = [
    {name = "gmcosta",email = "geu_costa@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'
asyncio_default_fixture_loop_scope = 'function'

[tool.coverage.run]
concurrency = ["thread", "greenlet"]

[tool.taskipy.tasks]
migrate = """
    bash -c '
    echo "📝 Digite uma mensagem para a migração (obrigatório):"
    read MSG

    if [ -z "$MSG" ]; then
    MSG="migration"
    fi

    echo "🧠 Verificando se o banco está acessível..."
    if ! alembic upgrade head --sql > /dev/null 2>&1; then
    echo "❌ Banco não acessível ou configuração incorreta (verifique o alembic.ini)"
    exit 1
    fi

    echo "🧹 Limpando stage do git..."
    git reset > /dev/null

    echo "🛠️ Gerando migração..."
    alembic revision --autogenerate -m "$MSG"

    if [ ! -d "migrations/versions" ]; then
    echo "❌ Diretório de migrações não encontrado (esperado: migrations/versions)"
    exit 1
    fi

    echo "💾 Commitando migração..."
    git add migrations/versions
    git commit -m "migration: $MSG" || echo "⚠️ Nenhuma migração commitada (possivelmente sem alterações)."

    echo "🚀 Aplicando migração..."
    alembic upgrade head

    echo "✅ Migração aplicada com sucesso!"
    '
    """
format = 'ruff check --fix; ruff format'
run = 'fastapi dev vitrine/app.py'
test = 'pytest -s -x --cov=vitrine -vv'
cov = 'coverage html'

[tool.poetry.dependencies]
fastapi = {extras = ["standard"], version = "^0.116.1"}
pydantic-settings = "^2.10.1"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.41"}
alembic = "^1.16.4"
pyjwt = "^2.10.1"
pwdlib = {extras = ["argon2"], version = "^0.2.1"}
aiosqlite = "^0.21.0"
psycopg = {extras = ["binary"], version = "^3.2.9"}
polars = "^1.31.0"
openpyxl = "^3.1.5"
xlrd = "^2.0.2"
python-calamine = "^0.4.0"
fastexcel = "^0.14.0"
python-jose = "^3.5.0"
testcontainers = {extras = ["mailpit"], version = "^4.13.1"}
apscheduler = "^3.11.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-cov = "^6.2.1"
taskipy = "^1.14.1"
ruff = "^0.12.5"
pytest-asyncio = "^1.1.0"
factory-boy = "^3.3.3"
freezegun = "^1.5.3"
testcontainers = "^4.12.0"

