"""tsv para user

Revision ID: 039a61e5d049
Revises: 3db2cdfecff3
Create Date: 2025-11-13 11:09:36.704421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '039a61e5d049'
down_revision: Union[str, Sequence[str], None] = '3db2cdfecff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(username, '') || ' ' || regexp_replace(coalesce(split_part(email, '@', 1), ''), '[@._-]', ' ', 'g'))", persisted=True), nullable=False))
    op.create_index('ix_user_tsv', 'users', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tsv', table_name='users', postgresql_using='gin')
    op.drop_column('users', 'tsv')
    # ### end Alembic commands ###
