"""tmp

Revision ID: 099ed9dcbbc9
Revises: cce7a7db904d
Create Date: 2025-08-19 20:35:06.526908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099ed9dcbbc9'
down_revision: Union[str, Sequence[str], None] = 'cce7a7db904d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalog_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_images')
    # ### end Alembic commands ###
