"""fix

Revision ID: 0c995d1fad26
Revises: d3b34d733f39
Create Date: 2025-11-07 15:49:55.685794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c995d1fad26'
down_revision: Union[str, Sequence[str], None] = 'd3b34d733f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(name, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=False))
    op.create_index('ix_role_tsv', 'roles', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_tsv', table_name='roles', postgresql_using='gin')
    op.drop_column('roles', 'tsv')
    # ### end Alembic commands ###
