"""added loanable item checks

Revision ID: 1201ee3f82ff
Revises: 95ef9c7c7a61
Create Date: 2026-03-17 17:23:24.319876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1201ee3f82ff'
down_revision: Union[str, Sequence[str], None] = '95ef9c7c7a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loanable_items', sa.Column('last_check', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loanable_items', 'last_check')
    # ### end Alembic commands ###
