"""empty message

Revision ID: 172ad14db8f5
Revises: 623aa5c3393b
Create Date: 2025-09-27 16:42:40.926024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172ad14db8f5'
down_revision: Union[str, Sequence[str], None] = '623aa5c3393b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_assets', sa.Column('location_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'inventory_assets', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_assets', type_='foreignkey')
    op.drop_column('inventory_assets', 'location_id')
    # ### end Alembic commands ###
