"""Add parecer_pdf to Collection

Revision ID: 22b69fee138b
Revises: a0591a7c273d
Create Date: 2026-05-27 18:39:30.763822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b69fee138b'
down_revision: Union[str, Sequence[str], None] = 'a0591a7c273d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('parecer_pdf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'parecer_pdf')
    # ### end Alembic commands ###
