"""dropped parecer_pdf due to repeated columns

Revision ID: 233b4919c958
Revises: e2cf0b43483a
Create Date: 2026-06-10 16:05:16.296795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233b4919c958'
down_revision: Union[str, Sequence[str], None] = 'e2cf0b43483a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'parecer_pdf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('parecer_pdf', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
