"""added is_visible to loanItems

Revision ID: 356c72253a33
Revises: 6c350325392e
Create Date: 2026-04-07 18:26:59.493700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356c72253a33'
down_revision: Union[str, Sequence[str], None] = '6c350325392e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loanable_items', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loanable_items', 'is_visible')
    # ### end Alembic commands ###
