"""empty message

Revision ID: 380713aab4f1
Revises: 70ec6051aa68
Create Date: 2025-09-30 00:47:56.887914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380713aab4f1'
down_revision: Union[str, Sequence[str], None] = '70ec6051aa68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_inventory', sa.Column('filled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_inventory', 'filled')
    # ### end Alembic commands ###
