"""empty message

Revision ID: 39b5c8dd26ee
Revises: a1d26583a35a
Create Date: 2025-08-19 23:42:10.755504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b5c8dd26ee'
down_revision: Union[str, Sequence[str], None] = 'a1d26583a35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencys', sa.Column('unit_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('agencys_agency_name_key'), 'agencys', type_='unique')
    op.create_unique_constraint('uq_agency_name_unit_id', 'agencys', ['agency_name', 'unit_id'])
    op.create_foreign_key(None, 'agencys', 'units', ['unit_id'], ['id'])
    op.add_column('catalog', sa.Column('location_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('catalog_unit_id_fkey'), 'catalog', type_='foreignkey')
    op.drop_constraint(op.f('catalog_agency_id_fkey'), 'catalog', type_='foreignkey')
    op.drop_constraint(op.f('catalog_sector_id_fkey'), 'catalog', type_='foreignkey')
    op.create_foreign_key(None, 'catalog', 'locations', ['location_id'], ['id'])
    op.drop_column('catalog', 'agency_id')
    op.drop_column('catalog', 'unit_id')
    op.drop_column('catalog', 'sector_id')
    op.drop_constraint(op.f('locations_location_name_key'), 'locations', type_='unique')
    op.create_unique_constraint('uq_location_name_sector_id', 'locations', ['location_name', 'sector_id'])
    op.add_column('sectors', sa.Column('agency_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('sectors_sector_name_key'), 'sectors', type_='unique')
    op.create_unique_constraint('uq_sector_name_agency_id', 'sectors', ['sector_name', 'agency_id'])
    op.drop_constraint(op.f('sectors_unit_id_fkey'), 'sectors', type_='foreignkey')
    op.create_foreign_key(None, 'sectors', 'agencys', ['agency_id'], ['id'])
    op.drop_column('sectors', 'unit_id')
    op.drop_constraint(op.f('units_unit_name_key'), 'units', type_='unique')
    op.create_unique_constraint('uq_unit_name_user_id', 'units', ['unit_name', 'user_id'])
    op.drop_constraint(op.f('units_agency_id_fkey'), 'units', type_='foreignkey')
    op.drop_column('units', 'agency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('agency_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('units_agency_id_fkey'), 'units', 'agencys', ['agency_id'], ['id'])
    op.drop_constraint('uq_unit_name_user_id', 'units', type_='unique')
    op.create_unique_constraint(op.f('units_unit_name_key'), 'units', ['unit_name'], postgresql_nulls_not_distinct=False)
    op.add_column('sectors', sa.Column('unit_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sectors', type_='foreignkey')
    op.create_foreign_key(op.f('sectors_unit_id_fkey'), 'sectors', 'units', ['unit_id'], ['id'])
    op.drop_constraint('uq_sector_name_agency_id', 'sectors', type_='unique')
    op.create_unique_constraint(op.f('sectors_sector_name_key'), 'sectors', ['sector_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('sectors', 'agency_id')
    op.drop_constraint('uq_location_name_sector_id', 'locations', type_='unique')
    op.create_unique_constraint(op.f('locations_location_name_key'), 'locations', ['location_name'], postgresql_nulls_not_distinct=False)
    op.add_column('catalog', sa.Column('sector_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('catalog', sa.Column('unit_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('catalog', sa.Column('agency_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'catalog', type_='foreignkey')
    op.create_foreign_key(op.f('catalog_sector_id_fkey'), 'catalog', 'sectors', ['sector_id'], ['id'])
    op.create_foreign_key(op.f('catalog_agency_id_fkey'), 'catalog', 'agencys', ['agency_id'], ['id'])
    op.create_foreign_key(op.f('catalog_unit_id_fkey'), 'catalog', 'units', ['unit_id'], ['id'])
    op.drop_column('catalog', 'location_id')
    op.drop_constraint(None, 'agencys', type_='foreignkey')
    op.drop_constraint('uq_agency_name_unit_id', 'agencys', type_='unique')
    op.create_unique_constraint(op.f('agencys_agency_name_key'), 'agencys', ['agency_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('agencys', 'unit_id')
    # ### end Alembic commands ###
