"""add_workflow_status_to_catalog

Revision ID: 3e94b2484831
Revises: 1201ee3f82ff
Create Date: 2026-03-26 20:12:58.816838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e94b2484831'
down_revision: Union[str, Sequence[str], None] = '1201ee3f82ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('current_workflow_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_catalog_current_workflow_status'), 'catalog', ['current_workflow_status'], unique=False)
    op.drop_index(op.f('idx_catalog_workflow_latest'), table_name='catalog_workflow')
    op.execute("""
        UPDATE catalog c
        SET current_workflow_status = cw.workflow_status
        FROM (
            SELECT catalog_id, workflow_status,
                   ROW_NUMBER() OVER(PARTITION BY catalog_id ORDER BY created_at DESC) as rn
            FROM catalog_workflow
        ) cw
        WHERE c.id = cw.catalog_id AND cw.rn = 1;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_catalog_workflow_latest'), 'catalog_workflow', ['catalog_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_catalog_current_workflow_status'), table_name='catalog')
    op.drop_column('catalog', 'current_workflow_status')
    # ### end Alembic commands ###
