"""empty message

Revision ID: 42db0efca478
Revises: a1ae8a1d6234
Create Date: 2025-08-22 12:05:50.439995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42db0efca478'
down_revision: Union[str, Sequence[str], None] = 'a1ae8a1d6234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_unit_id_fkey'), 'assets', type_='foreignkey')
    op.drop_constraint(op.f('assets_agency_id_fkey'), 'assets', type_='foreignkey')
    op.drop_constraint(op.f('assets_sector_id_fkey'), 'assets', type_='foreignkey')
    op.drop_column('assets', 'unit_id')
    op.drop_column('assets', 'sector_id')
    op.drop_column('assets', 'agency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('agency_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('sector_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('unit_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('assets_sector_id_fkey'), 'assets', 'sectors', ['sector_id'], ['id'])
    op.create_foreign_key(op.f('assets_agency_id_fkey'), 'assets', 'agencys', ['agency_id'], ['id'])
    op.create_foreign_key(op.f('assets_unit_id_fkey'), 'assets', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###
