"""empty message

Revision ID: 455b7d6d043d
Revises: e23313949eca
Create Date: 2025-08-25 21:35:05.813398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455b7d6d043d'
down_revision: Union[str, Sequence[str], None] = 'e23313949eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('legal_guardian_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['legal_guardian_id'], ['legal_guardians.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_guardian_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('inventory_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inventory_owner_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['inventory_owner_id'], ['inventory_owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_owner_id', 'asset_id', name='uq_inventory_owner_asset')
    )
    op.create_index(op.f('ix_inventory_assets_status'), 'inventory_assets', ['status'], unique=False)
    op.create_table('favorite_catalogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'catalog_id', name='uq_favorite_catalog')
    )
    op.create_index(op.f('ix_assets_asset_check_digit'), 'assets', ['asset_check_digit'], unique=False)
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=False)
    op.create_index(op.f('ix_assets_atm_number'), 'assets', ['atm_number'], unique=False)
    op.add_column('inventory', sa.Column('available', sa.Boolean(), nullable=False))
    op.add_column('locations', sa.Column('legal_guardian_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_location_name_sector_id'), 'locations', type_='unique')
    op.create_unique_constraint('uq_location_name_sector_lg_id', 'locations', ['location_name', 'sector_id', 'legal_guardian_id'])
    op.create_foreign_key(None, 'locations', 'legal_guardians', ['legal_guardian_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint('uq_location_name_sector_lg_id', 'locations', type_='unique')
    op.create_unique_constraint(op.f('uq_location_name_sector_id'), 'locations', ['location_name', 'sector_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('locations', 'legal_guardian_id')
    op.drop_column('inventory', 'available')
    op.drop_index(op.f('ix_assets_atm_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_check_digit'), table_name='assets')
    op.drop_table('favorite_catalogs')
    op.drop_index(op.f('ix_inventory_assets_status'), table_name='inventory_assets')
    op.drop_table('inventory_assets')
    op.drop_table('system_identities')
    # ### end Alembic commands ###
