"""empty message

Revision ID: 46eb36d7a37c
Revises: b8ff1bca8031
Create Date: 2025-10-19 23:04:35.555371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46eb36d7a37c'
down_revision: Union[str, Sequence[str], None] = 'b8ff1bca8031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_agency_name_unit_id'), 'agencys', type_='unique')
    op.create_index('ix_uq_agencys_agency_name_unit_id_active', 'agencys', ['agency_name', 'unit_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('assets_asset_code_asset_check_digit_key'), 'assets', type_='unique')
    op.create_index('ix_uq_assets_asset_code_asset_check_digit_active', 'assets', ['asset_code', 'asset_check_digit'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_collection_user_name'), 'collections', type_='unique')
    op.create_index('ix_uq_collections_user_id_name_active', 'collections', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_inventory_key'), 'inventory', type_='unique')
    op.create_index('ix_uq_inventory_key_active', 'inventory', ['key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_location_inventory_asset'), 'inventory_assets', type_='unique')
    op.create_index('ix_uq_inventory_assets_location_inventory_asset_active', 'inventory_assets', ['location_inventory_id', 'asset_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('legal_guardians_legal_guardians_name_key'), 'legal_guardians', type_='unique')
    op.create_index('ix_uq_legal_guardians_name_active', 'legal_guardians', ['legal_guardians_name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_location_name_sector_lg_id'), 'locations', type_='unique')
    op.create_index('ix_uq_locations_location_name_sector_lg_id_active', 'locations', ['location_name', 'sector_id', 'legal_guardian_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('materials_material_name_key'), 'materials', type_='unique')
    op.create_index('ix_uq_materials_material_name_active', 'materials', ['material_name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    op.create_index('ix_uq_permissions_code_active', 'permissions', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_permissions_name_active', 'permissions', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_role_permission'), 'role_permissions', type_='unique')
    op.create_index('ix_uq_role_permissions_role_id_permission_id_active', 'role_permissions', ['role_id', 'permission_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index('ix_uq_roles_name_active', 'roles', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_sector_name_agency_id'), 'sectors', type_='unique')
    op.create_index('ix_uq_sectors_sector_name_agency_id_active', 'sectors', ['sector_name', 'agency_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('system_identities_legal_guardian_id_key'), 'system_identities', type_='unique')
    op.drop_constraint(op.f('system_identities_user_id_key'), 'system_identities', type_='unique')
    op.create_index('ix_uq_system_identities_legal_guardian_id_active', 'system_identities', ['legal_guardian_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_system_identities_user_id_active', 'system_identities', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_index('ix_uq_system_settings_key_active', 'system_settings', ['key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_unit_name_user_id'), 'units', type_='unique')
    op.create_index('ix_uq_units_unit_name_user_id_active', 'units', ['unit_name', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_user_notification'), 'user_notifications', type_='unique')
    op.create_index('ix_uq_user_notifications_notification_id_target_user_id_active', 'user_notifications', ['notification_id', 'target_user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_user_role'), 'user_roles', type_='unique')
    op.create_index('ix_uq_user_roles_user_id_role_id_active', 'user_roles', ['user_id', 'role_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index('ix_uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_uq_users_username_active', 'users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_users_username_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_user_roles_user_id_role_id_active', table_name='user_roles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_user_role'), 'user_roles', ['user_id', 'role_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_user_notifications_notification_id_target_user_id_active', table_name='user_notifications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_user_notification'), 'user_notifications', ['notification_id', 'target_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_units_unit_name_user_id_active', table_name='units', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_unit_name_user_id'), 'units', ['unit_name', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_system_settings_key_active', table_name='system_settings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.drop_index('ix_uq_system_identities_user_id_active', table_name='system_identities', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_system_identities_legal_guardian_id_active', table_name='system_identities', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('system_identities_user_id_key'), 'system_identities', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('system_identities_legal_guardian_id_key'), 'system_identities', ['legal_guardian_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_sectors_sector_name_agency_id_active', table_name='sectors', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_sector_name_agency_id'), 'sectors', ['sector_name', 'agency_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_roles_name_active', table_name='roles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_role_permissions_role_id_permission_id_active', table_name='role_permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_role_permission'), 'role_permissions', ['role_id', 'permission_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_permissions_name_active', table_name='permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_uq_permissions_code_active', table_name='permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('permissions_name_key'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_materials_material_name_active', table_name='materials', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('materials_material_name_key'), 'materials', ['material_name'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_locations_location_name_sector_lg_id_active', table_name='locations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_location_name_sector_lg_id'), 'locations', ['location_name', 'sector_id', 'legal_guardian_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_legal_guardians_name_active', table_name='legal_guardians', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('legal_guardians_legal_guardians_name_key'), 'legal_guardians', ['legal_guardians_name'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_inventory_assets_location_inventory_asset_active', table_name='inventory_assets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_location_inventory_asset'), 'inventory_assets', ['location_inventory_id', 'asset_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_inventory_key_active', table_name='inventory', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_inventory_key'), 'inventory', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_collections_user_id_name_active', table_name='collections', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_collection_user_name'), 'collections', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_assets_asset_code_asset_check_digit_active', table_name='assets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('assets_asset_code_asset_check_digit_key'), 'assets', ['asset_code', 'asset_check_digit'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_uq_agencys_agency_name_unit_id_active', table_name='agencys', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_agency_name_unit_id'), 'agencys', ['agency_name', 'unit_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
