"""new temporary files table

Revision ID: 47a081a79f71
Revises: 54feb5f1e826
Create Date: 2026-04-29 19:24:43.823876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a081a79f71'
down_revision: Union[str, Sequence[str], None] = '54feb5f1e826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_temporary_files_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_temporary_files_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_temporary_files_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporary_files_token'), 'temporary_files', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_files_token'), table_name='temporary_files')
    op.drop_table('temporary_files')
    # ### end Alembic commands ###
