"""adicionando colunas de auditoria em loans

Revision ID: 6c350325392e
Revises: 3e94b2484831
Create Date: 2026-04-07 17:51:53.371665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c350325392e'
down_revision: Union[str, Sequence[str], None] = '3e94b2484831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('confirmed_by_id', sa.Uuid(), nullable=True))
    op.add_column('loans', sa.Column('executed_by_id', sa.Uuid(), nullable=True))
    op.add_column('loans', sa.Column('returned_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'loans', 'users', ['executed_by_id'], ['id'])
    op.create_foreign_key(None, 'loans', 'users', ['returned_by_id'], ['id'])
    op.create_foreign_key(None, 'loans', 'users', ['confirmed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'returned_by_id')
    op.drop_column('loans', 'executed_by_id')
    op.drop_column('loans', 'confirmed_by_id')
    # ### end Alembic commands ###
