"""create loanable items and loans tables

Revision ID: 6c4d75612a2d
Revises: c81b5a63ef27
Create Date: 2026-02-26 16:34:30.430440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4d75612a2d'
down_revision: Union[str, Sequence[str], None] = 'c81b5a63ef27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loanable_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalog_id', sa.Uuid(), nullable=False),
    sa.Column('legal_guardian_id', sa.Uuid(), nullable=False),
    sa.Column('owner_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_loanable_items_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_loanable_items_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['legal_guardian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_loanable_items_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id')
    )
    op.create_table('loans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loanable_item_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('temporary_guardian_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_executed', sa.Boolean(), nullable=False),
    sa.Column('is_returned', sa.Boolean(), nullable=False),
    sa.Column('is_maintenance', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_loans_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_loans_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['loanable_item_id'], ['loanable_items.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temporary_guardian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_loans_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_transfer_documents_deleted_by', 'transfer_documents', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_transfer_documents_updated_by', 'transfer_documents', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_transfer_documents_created_by', 'transfer_documents', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_transfer_signers_updated_by', 'transfer_signers', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_transfer_signers_deleted_by', 'transfer_signers', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_transfer_signers_created_by', 'transfer_signers', 'users', ['created_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transfer_signers_created_by', 'transfer_signers', type_='foreignkey')
    op.drop_constraint('fk_transfer_signers_deleted_by', 'transfer_signers', type_='foreignkey')
    op.drop_constraint('fk_transfer_signers_updated_by', 'transfer_signers', type_='foreignkey')
    op.drop_constraint('fk_transfer_documents_created_by', 'transfer_documents', type_='foreignkey')
    op.drop_constraint('fk_transfer_documents_updated_by', 'transfer_documents', type_='foreignkey')
    op.drop_constraint('fk_transfer_documents_deleted_by', 'transfer_documents', type_='foreignkey')
    op.drop_table('loans')
    op.drop_table('loanable_items')
    # ### end Alembic commands ###
