"""empty message

Revision ID: 70ec6051aa68
Revises: 172ad14db8f5
Create Date: 2025-09-29 23:40:50.838203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70ec6051aa68'
down_revision: Union[str, Sequence[str], None] = '172ad14db8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'location_inventory',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('inventory_id', sa.Uuid(), nullable=False),
        sa.Column('location_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id']),
        sa.ForeignKeyConstraint(['location_id'], ['locations.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('inventory_id', 'location_id', name='uq_inventory_location')
    )

    op.add_column('inventory_assets', sa.Column('location_inventory_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_inventory_owner_asset'), 'inventory_assets', type_='unique')
    op.create_unique_constraint('uq_location_inventory_asset', 'inventory_assets', ['location_inventory_id', 'asset_id'])
    op.drop_constraint(op.f('inventory_assets_inventory_owner_id_fkey'), 'inventory_assets', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_assets', 'location_inventory', ['location_inventory_id'], ['id'])
    op.drop_column('inventory_assets', 'inventory_owner_id')

    op.drop_table('inventory_owners')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_assets', sa.Column('inventory_owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory_assets', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_assets_inventory_owner_id_fkey'), 'inventory_assets', 'inventory_owners', ['inventory_owner_id'], ['id'])
    op.drop_constraint('uq_location_inventory_asset', 'inventory_assets', type_='unique')
    op.create_unique_constraint(op.f('uq_inventory_owner_asset'), 'inventory_assets', ['inventory_owner_id', 'asset_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('inventory_assets', 'location_inventory_id')
    op.create_table('inventory_owners',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inventory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('inventory_owners_inventory_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('inventory_owners_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_owners_pkey')),
    sa.UniqueConstraint('inventory_id', 'user_id', name=op.f('uq_inventory_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('location_inventory')
    # ### end Alembic commands ###
