"""empty message

Revision ID: 7b1162f5ce68
Revises: 3c33f47f5708
Create Date: 2025-08-22 15:15:03.170495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b1162f5ce68'
down_revision: Union[str, Sequence[str], None] = '3c33f47f5708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog', 'situation',
               existing_type=postgresql.ENUM('NORMAL', 'NOT_INVENTORIED', 'REGISTERED', 'AWAITING_ACCEPTANCE', 'MOVED', name='asset_situation_enum'),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_catalog_situation'), 'catalog', ['situation'], unique=False)
    op.alter_column('catalog_workflow', 'workflow_status',
               existing_type=postgresql.ENUM('STARTED', 'REVIEW_REQUESTED', 'ADJUSTMENT_REQUESTED', 'COMPLETED', name='workflow_status_enum'),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_catalog_workflow_workflow_status'), 'catalog_workflow', ['workflow_status'], unique=False)
    op.alter_column('inventory_assets', 'inventory_status',
               existing_type=postgresql.ENUM('GOOD', 'NOT_FOUND', 'IRRECOVERABLE', 'UNECONOMICAL', name='inventory_status_enum'),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_inventory_assets_inventory_status'), 'inventory_assets', ['inventory_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_assets_inventory_status'), table_name='inventory_assets')
    op.alter_column('inventory_assets', 'inventory_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('GOOD', 'NOT_FOUND', 'IRRECOVERABLE', 'UNECONOMICAL', name='inventory_status_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_catalog_workflow_workflow_status'), table_name='catalog_workflow')
    op.alter_column('catalog_workflow', 'workflow_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('STARTED', 'REVIEW_REQUESTED', 'ADJUSTMENT_REQUESTED', 'COMPLETED', name='workflow_status_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_catalog_situation'), table_name='catalog')
    op.alter_column('catalog', 'situation',
               existing_type=sa.String(),
               type_=postgresql.ENUM('NORMAL', 'NOT_INVENTORIED', 'REGISTERED', 'AWAITING_ACCEPTANCE', 'MOVED', name='asset_situation_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
