"""empty message

Revision ID: 7d284e5fadf5
Revises: 3355f129b70c
Create Date: 2025-10-19 02:04:53.451662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d284e5fadf5'
down_revision: Union[str, Sequence[str], None] = '3355f129b70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'target_user_id', name='uq_user_notification')
    )
    op.create_index(op.f('ix_user_notifications_notification_id'), 'user_notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_target_user_id'), 'user_notifications', ['target_user_id'], unique=False)
    op.drop_constraint(op.f('notifications_target_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'target_user_id')
    op.drop_column('notifications', 'read_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('target_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notifications_target_user_id_fkey'), 'notifications', 'users', ['target_user_id'], ['id'])
    op.drop_index(op.f('ix_user_notifications_target_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
