"""changed collection naming constraint

Revision ID: 8f65e7d90a44
Revises: 233b4919c958
Create Date: 2026-06-15 19:49:42.009988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f65e7d90a44'
down_revision: Union[str, Sequence[str], None] = '233b4919c958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uq_collections_user_id_name_active'), table_name='collections', postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_uq_collections_user_id_name_active', 'collections', ['user_id', 'name', 'type'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_collections_user_id_name_active', table_name='collections', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_uq_collections_user_id_name_active'), 'collections', ['user_id', 'name'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
