"""empty message

Revision ID: 95e12b0fcb3b
Revises: 455b7d6d043d
Create Date: 2025-08-27 15:18:57.908235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e12b0fcb3b'
down_revision: Union[str, Sequence[str], None] = '455b7d6d043d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_transfer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['catalog_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_transfer_location_id'), 'workflow_transfer', ['location_id'], unique=False)
    op.create_index(op.f('ix_workflow_transfer_status'), 'workflow_transfer', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_transfer_user_id'), 'workflow_transfer', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_transfer_workflow_id'), 'workflow_transfer', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_transfer_workflow_id'), table_name='workflow_transfer')
    op.drop_index(op.f('ix_workflow_transfer_user_id'), table_name='workflow_transfer')
    op.drop_index(op.f('ix_workflow_transfer_status'), table_name='workflow_transfer')
    op.drop_index(op.f('ix_workflow_transfer_location_id'), table_name='workflow_transfer')
    op.drop_table('workflow_transfer')
    # ### end Alembic commands ###
