"""add in_maintenance column

Revision ID: 95ef9c7c7a61
Revises: dc240293c568
Create Date: 2026-03-16 17:18:33.788310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ef9c7c7a61'
down_revision: Union[str, Sequence[str], None] = 'dc240293c568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loanable_items', sa.Column('in_maintenance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loanable_items', 'in_maintenance')
    # ### end Alembic commands ###
