"""tsv para patrimonios

Revision ID: 9fa92b177e20
Revises: b5245bc827a8
Create Date: 2025-08-04 16:26:51.341298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fa92b177e20'
down_revision: Union[str, Sequence[str], None] = 'b5245bc827a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(asset_code, '') || ' ' || coalesce(serial_number, '') || ' ' || coalesce(asset_description, '') || ' ' || coalesce(item_brand, '') || ' ' || coalesce(item_model, '') || ' ' || coalesce(atm_number, ''))", persisted=True), nullable=False))
    op.drop_constraint(op.f('assets_asset_code_asset_check_digit_key'), 'assets', type_='unique')
    op.create_index('ix_assets_tsv', 'assets', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_tsv', table_name='assets', postgresql_using='gin')
    op.create_unique_constraint(op.f('assets_asset_code_asset_check_digit_key'), 'assets', ['asset_code', 'asset_check_digit'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'tsv')
    # ### end Alembic commands ###
