"""changes collections

Revision ID: a0591a7c273d
Revises: 26c4429c6fda
Create Date: 2026-05-18 17:27:29.311171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0591a7c273d'
down_revision: Union[str, Sequence[str], None] = '26c4429c6fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_items', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('collection_items', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('collections', sa.Column('document_path', sa.String(), nullable=True))
    op.add_column('collections', sa.Column('sei_process', sa.String(), nullable=True))
    op.add_column('collections', sa.Column('parecer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'parecer')
    op.drop_column('collections', 'sei_process')
    op.drop_column('collections', 'document_path')
    op.drop_column('collection_items', 'is_approved')
    op.drop_column('collection_items', 'is_locked')
    # ### end Alembic commands ###
