"""empty message

Revision ID: a1ae8a1d6234
Revises: 39b5c8dd26ee
Create Date: 2025-08-20 12:04:19.633874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1ae8a1d6234'
down_revision: Union[str, Sequence[str], None] = '39b5c8dd26ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog', 'conservation_status',
               existing_type=postgresql.ENUM('GOOD', 'UNECONOMICAL', 'IRRECOVERABLE', 'IDLE', 'RECOVERABLE', name='conservation_status_enum'),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog', 'conservation_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('GOOD', 'UNECONOMICAL', 'IRRECOVERABLE', 'IDLE', 'RECOVERABLE', name='conservation_status_enum'),
               nullable=False)
    # ### end Alembic commands ###
