"""Adicionando nova localização no anuncio

Revision ID: a1d26583a35a
Revises: 099ed9dcbbc9
Create Date: 2025-08-19 21:00:59.023893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d26583a35a'
down_revision: Union[str, Sequence[str], None] = '099ed9dcbbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('agency_id', sa.Uuid(), nullable=True))
    op.add_column('catalog', sa.Column('unit_id', sa.Uuid(), nullable=True))
    op.add_column('catalog', sa.Column('sector_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'catalog', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'catalog', 'sectors', ['sector_id'], ['id'])
    op.create_foreign_key(None, 'catalog', 'agencys', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog', type_='foreignkey')
    op.drop_constraint(None, 'catalog', type_='foreignkey')
    op.drop_constraint(None, 'catalog', type_='foreignkey')
    op.drop_column('catalog', 'sector_id')
    op.drop_column('catalog', 'unit_id')
    op.drop_column('catalog', 'agency_id')
    # ### end Alembic commands ###
