"""tsv para buscas textuais

Revision ID: b5245bc827a8
Revises: 682a368556d5
Create Date: 2025-08-01 11:39:24.572511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5245bc827a8'
down_revision: Union[str, Sequence[str], None] = '682a368556d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencys', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(agency_name, '') || ' ' || coalesce(agency_code, ''))", persisted=True), nullable=False))
    op.create_index('ix_agencys_tsv', 'agencys', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('legal_guardians', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(legal_guardians_name, '') || ' ' || coalesce(legal_guardians_code, ''))", persisted=True), nullable=False))
    op.create_index('ix_legal_guardians_tsv', 'legal_guardians', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('locations', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(location_name, '') || ' ' || coalesce(location_code, ''))", persisted=True), nullable=False))
    op.create_index('ix_locations_tsv', 'locations', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('materials', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(material_name, '') || ' ' || coalesce(material_code, ''))", persisted=True), nullable=False))
    op.create_index('ix_materials_tsv', 'materials', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('sectors', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(sector_name, '') || ' ' || coalesce(sector_code, ''))", persisted=True), nullable=False))
    op.create_index('ix_sectors_tsv', 'sectors', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('units', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', coalesce(unit_name, '') || ' ' || coalesce(unit_code, '') || ' ' || coalesce(unit_siaf, ''))", persisted=True), nullable=False))
    op.create_index('ix_units_tsv', 'units', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_units_tsv', table_name='units', postgresql_using='gin')
    op.drop_column('units', 'tsv')
    op.drop_index('ix_sectors_tsv', table_name='sectors', postgresql_using='gin')
    op.drop_column('sectors', 'tsv')
    op.drop_index('ix_materials_tsv', table_name='materials', postgresql_using='gin')
    op.drop_column('materials', 'tsv')
    op.drop_index('ix_locations_tsv', table_name='locations', postgresql_using='gin')
    op.drop_column('locations', 'tsv')
    op.drop_index('ix_legal_guardians_tsv', table_name='legal_guardians', postgresql_using='gin')
    op.drop_column('legal_guardians', 'tsv')
    op.drop_index('ix_agencys_tsv', table_name='agencys', postgresql_using='gin')
    op.drop_column('agencys', 'tsv')
    # ### end Alembic commands ###
