"""create_transfer_tables

Revision ID: c81b5a63ef27
Revises: 4f657c2a782d
Create Date: 2026-01-21 15:28:24.825364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81b5a63ef27'
down_revision: Union[str, Sequence[str], None] = '4f657c2a782d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalog_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_transfer_documents_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_transfer_documents_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_transfer_documents_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_documents_status'), 'transfer_documents', ['status'], unique=False)
    op.create_table('transfer_signers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transfer_document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('signedAt', sa.DateTime(), nullable=True),
    sa.Column('isSigned', sa.Boolean(), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_transfer_signers_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='fk_transfer_signers_deleted_by', use_alter=True),
    sa.ForeignKeyConstraint(['transfer_document_id'], ['transfer_documents.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_transfer_signers_updated_by', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_signers_token'), 'transfer_signers', ['token'], unique=False)
    op.create_index('ix_uq_transfer_signers_token_active', 'transfer_signers', ['token'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uq_transfer_signers_token_active', table_name='transfer_signers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_transfer_signers_token'), table_name='transfer_signers')
    op.drop_table('transfer_signers')
    op.drop_index(op.f('ix_transfer_documents_status'), table_name='transfer_documents')
    op.drop_table('transfer_documents')
    # ### end Alembic commands ###
