"""nivel de hierarquia para uni/sec/loc/uge

Revision ID: cce7a7db904d
Revises: fd814ccceed3
Create Date: 2025-08-08 01:10:41.348157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce7a7db904d'
down_revision: Union[str, Sequence[str], None] = 'fd814ccceed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agencys_agency_code_key'), 'agencys', type_='unique')
    op.create_unique_constraint(None, 'agencys', ['agency_name'])
    op.create_unique_constraint(None, 'assets', ['asset_code', 'asset_check_digit'])
    op.add_column('locations', sa.Column('sector_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'locations', 'sectors', ['sector_id'], ['id'])
    op.add_column('sectors', sa.Column('unit_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'sectors', 'units', ['unit_id'], ['id'])
    op.add_column('units', sa.Column('agency_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_unit'), 'units', type_='unique')
    op.create_unique_constraint(None, 'units', ['unit_name'])
    op.create_foreign_key(None, 'units', 'agencys', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_constraint(None, 'units', type_='unique')
    op.create_unique_constraint(op.f('uq_unit'), 'units', ['unit_name', 'unit_siaf'], postgresql_nulls_not_distinct=False)
    op.drop_column('units', 'agency_id')
    op.drop_constraint(None, 'sectors', type_='foreignkey')
    op.drop_column('sectors', 'unit_id')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'sector_id')
    op.drop_constraint(None, 'assets', type_='unique')
    op.drop_constraint(None, 'agencys', type_='unique')
    op.create_unique_constraint(op.f('agencys_agency_code_key'), 'agencys', ['agency_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
