"""add indexes to catalog relations

Revision ID: d5f2182adf3e
Revises: 356c72253a33
Create Date: 2026-04-28 15:37:23.328787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f2182adf3e'
down_revision: Union[str, Sequence[str], None] = '356c72253a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_catalog_user_id'), 'catalog', ['user_id'], unique=False)
    op.create_index(op.f('ix_catalog_files_catalog_id'), 'catalog_files', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_catalog_images_catalog_id'), 'catalog_images', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_catalog_workflow_catalog_id'), 'catalog_workflow', ['catalog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_workflow_catalog_id'), table_name='catalog_workflow')
    op.drop_index(op.f('ix_catalog_images_catalog_id'), table_name='catalog_images')
    op.drop_index(op.f('ix_catalog_files_catalog_id'), table_name='catalog_files')
    op.drop_index(op.f('ix_catalog_user_id'), table_name='catalog')
    # ### end Alembic commands ###
