"""update loan table with return details

Revision ID: dc240293c568
Revises: 6c4d75612a2d
Create Date: 2026-03-03 10:42:08.591344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc240293c568'
down_revision: Union[str, Sequence[str], None] = '6c4d75612a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_loanable_items_updated_by', 'loanable_items', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_loanable_items_deleted_by', 'loanable_items', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_loanable_items_created_by', 'loanable_items', 'users', ['created_by'], ['id'], use_alter=True)
    op.add_column('loans', sa.Column('returned_at', sa.DateTime(), nullable=True))
    op.add_column('loans', sa.Column('lend_detail', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('returned_detail', sa.String(), nullable=True))
    op.create_foreign_key('fk_loans_updated_by', 'loans', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_loans_deleted_by', 'loans', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_loans_created_by', 'loans', 'users', ['created_by'], ['id'], use_alter=True)
    op.drop_column('loans', 'detail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('detail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_loans_created_by', 'loans', type_='foreignkey')
    op.drop_constraint('fk_loans_deleted_by', 'loans', type_='foreignkey')
    op.drop_constraint('fk_loans_updated_by', 'loans', type_='foreignkey')
    op.drop_column('loans', 'returned_detail')
    op.drop_column('loans', 'lend_detail')
    op.drop_column('loans', 'returned_at')
    op.drop_constraint('fk_loanable_items_created_by', 'loanable_items', type_='foreignkey')
    op.drop_constraint('fk_loanable_items_deleted_by', 'loanable_items', type_='foreignkey')
    op.drop_constraint('fk_loanable_items_updated_by', 'loanable_items', type_='foreignkey')
    # ### end Alembic commands ###
