"""empty message

Revision ID: e23313949eca
Revises: 7b1162f5ce68
Create Date: 2025-08-24 11:36:13.894188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e23313949eca'
down_revision: Union[str, Sequence[str], None] = '7b1162f5ce68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_owners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id', 'user_id', name='uq_inventory_user')
    )
    op.drop_index(op.f('ix_inventory_assets_inventory_status'), table_name='inventory_assets')
    op.drop_table('inventory_assets')
    op.add_column('inventory', sa.Column('key', sa.String(), nullable=False))
    op.add_column('inventory', sa.Column('created_by_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_inventory_location_term'), 'inventory', type_='unique')
    op.create_unique_constraint('uq_inventory_key', 'inventory', ['key'])
    op.drop_constraint(op.f('inventory_user_id_fkey'), 'inventory', type_='foreignkey')
    op.drop_constraint(op.f('inventory_location_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'users', ['created_by_id'], ['id'])
    op.drop_column('inventory', 'location_id')
    op.drop_column('inventory', 'term')
    op.drop_column('inventory', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_location_id_fkey'), 'inventory', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('inventory_user_id_fkey'), 'inventory', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_inventory_key', 'inventory', type_='unique')
    op.create_unique_constraint(op.f('uq_inventory_location_term'), 'inventory', ['location_id', 'term'], postgresql_nulls_not_distinct=False)
    op.drop_column('inventory', 'created_by_id')
    op.drop_column('inventory', 'key')
    op.create_table('inventory_assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inventory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inventory_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('inventory_assets_asset_id_fkey')),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('inventory_assets_inventory_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_assets_pkey')),
    sa.UniqueConstraint('inventory_id', 'asset_id', name=op.f('uq_inventory_asset'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_inventory_assets_inventory_status'), 'inventory_assets', ['inventory_status'], unique=False)
    op.drop_table('inventory_owners')
    # ### end Alembic commands ###
