"""Remove parecer and is_locked columns

Revision ID: e2cf0b43483a
Revises: 22b69fee138b
Create Date: 2026-05-27 20:26:25.488701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cf0b43483a'
down_revision: Union[str, Sequence[str], None] = '22b69fee138b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_items', 'is_locked')
    op.drop_column('collections', 'parecer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('parecer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('collection_items', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
