"""empty message

Revision ID: ec5d9ab44bca
Revises: c010bc979649
Create Date: 2025-10-07 13:54:55.519951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5d9ab44bca'
down_revision: Union[str, Sequence[str], None] = 'c010bc979649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_items', sa.Column('catalog_id', sa.Uuid(), nullable=False))
    op.add_column('collection_items', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('collection_items', sa.Column('comment', sa.String(), nullable=True))
    op.drop_index(op.f('ix_collection_items_item_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_item_type'), table_name='collection_items')
    op.drop_constraint(op.f('uq_collection_item'), 'collection_items', type_='unique')
    op.create_index(op.f('ix_collection_items_catalog_id'), 'collection_items', ['catalog_id'], unique=False)
    op.create_unique_constraint('uq_collection_catalog_item', 'collection_items', ['collection_id', 'catalog_id'])
    op.create_foreign_key(None, 'collection_items', 'catalog', ['catalog_id'], ['id'])
    op.drop_column('collection_items', 'item_id')
    op.drop_column('collection_items', 'item_type')
    op.add_column('collections', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'type')
    op.add_column('collection_items', sa.Column('item_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('collection_items', sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'collection_items', type_='foreignkey')
    op.drop_constraint('uq_collection_catalog_item', 'collection_items', type_='unique')
    op.drop_index(op.f('ix_collection_items_catalog_id'), table_name='collection_items')
    op.create_unique_constraint(op.f('uq_collection_item'), 'collection_items', ['collection_id', 'item_id', 'item_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_collection_items_item_type'), 'collection_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_collection_items_item_id'), 'collection_items', ['item_id'], unique=False)
    op.drop_column('collection_items', 'comment')
    op.drop_column('collection_items', 'status')
    op.drop_column('collection_items', 'catalog_id')
    # ### end Alembic commands ###
