"""adicionando regras de unicidade

Revision ID: fd814ccceed3
Revises: 9fa92b177e20
Create Date: 2025-08-04 16:41:21.621509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd814ccceed3'
down_revision: Union[str, Sequence[str], None] = '9fa92b177e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agencys', ['agency_code'])
    op.create_unique_constraint(None, 'legal_guardians', ['legal_guardians_name'])
    op.create_unique_constraint(None, 'locations', ['location_name'])
    op.create_unique_constraint(None, 'materials', ['material_name'])
    op.create_unique_constraint(None, 'sectors', ['sector_name'])
    op.create_unique_constraint('uq_unit', 'units', ['unit_name', 'unit_siaf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_unit', 'units', type_='unique')
    op.drop_constraint(None, 'sectors', type_='unique')
    op.drop_constraint(None, 'materials', type_='unique')
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_constraint(None, 'legal_guardians', type_='unique')
    op.drop_constraint(None, 'agencys', type_='unique')
    # ### end Alembic commands ###
